export const localization = {
    "ru": {
        'noMessage':'Уведомлений нет',
        'regPopUp':'Ваш пароль отправлен на указанную почту',
        'helpSearch': 'Введите слова поиска',
        'Catalog': 'Каталог',
        'Help': 'Помощь',
        'Other': 'Прочее',
        'Favorites': 'Избранное',
        'Glossary': 'Словарь',
        'ContactBroker': 'Связь с брокером',
        'OurApps': 'Торговое приложение',
        'OurWebsite': 'Наш сайт',
        'LanguagePreference': 'Выбор языка',
        'YouLoggedAs': 'Вы вошли как ',
        'LogInToTheAccount': 'Войти в аккаунт',
        'ManagerWillContact': 'Менеджер скоро с Вами свяжется',
        'thanks': 'Спасибо!',
        'createAccount': 'Cоздать аккаунт',
        "recvOffers": "Получить предложение",
        'Day': 'день',
        'Week': 'нед',
        "Authorization": "Авторизация",
        "More news": "Ещё новости",
        "Save": "Сохранить",
        "Specification": "Детализация",
        "Instruments": "Инструменты",
        "Session": "Сессия",
        "Time": "Время",
        "Home": "Главная",
        "Settings": "Настройки",
        'Buy': 'Покупать',
        'Sell': 'Продавать',
        'Neutral': 'Нейтрально',
        'Quote': 'Котировка',
        'Indicators': 'Показатели',
        'MovingAverages': 'Скользящие средние',
        'Hour': 'час',
        'min': 'мин',
        'LastUpdate': 'Последнее обновление',
        "Yes": "Да",
        "No": "Нет",
        "OK": "ОК",
        "News": "Новости",
        "Cancel": "Отмена",
        "login": "Войти",
        "turnBtn": "Свернуть все",
        "exit": "Выход",
        "notifications": "Уведомления",
        "error!": "Ошибка!",
        "signup": "Зарегистрируйтесь",
        "signup2": "Зарегистрироваться",
        "introduced": "Ознакомлен",
        "Country": "Страна",
        "Last tool cannot be removed from favorites": "Последний инструмент невозможно удалить из списка избранных ",
        "Registration": "Регистрация",
        "To get full access to the instruments...": "Чтобы получить полный доступ к инструментам, Вам необходимо войти в систему",
        "Are you sure you want to log out?": "Вы уверены, что хотите выйти ?",
        "Thank you for joining us!": "Спасибо,\n\r что присоеденились к нам!",
        "A letter to confirm your data...": "Письмо для подтверждения Ваших данных и завершения процесса регистрации отправлено на указаный e-mail",
        "Instructions for password recovery...": "Инструкция\n\r по восстановлению пароля отправлена на почту пользователя",
        "Something went wrong": "что - то пошло не так",
        "Invalid email address or server error": "Неверный адрес электронной почты или ошибка сервера",
        "Invalid email address or password": "Неверный адрес электронной почты или пароль",
        "Password recovery": "Восстановление пароля",
        "Please specify the email you used when registering": "Пожалуйста, укажите e-mail, который Вы использовали при регистрации",
        "Email-entry error": "Ошибка ввода e-mail",
        "Forgot password?": "Забыли пароль?",
        "Password failed": "Ошибка ввода пароля",
        "Already have an account?": "Уже есть аккаунт ?",
        "I have read and agree with": "Заполняя форму регистрации, я принимаю",
        "user agreement": "условия обработки персональных данных.",
        "user agreement2": "Пользовательское соглашение",
        "Enter your country": "Укажите страну",
        "10 characters minimum": "Минимальное количество 10 символов",
        "Leave a comment": "Оставить комментарий",
        "Liked the application":"Понравилось приложение?\nОцените его!",
        "Remind me later": "Напомнить позже",
        "tabbar": {
            "currency": "Валюты",
            "commodity": "Товары",
            "index": "Индексы",
            "stock": "Акции",
            "home": "Главная"
        },
        "Languages": {
            "Russian": "Русский",
            "English": "Английский",
            "Spanish": "Испанский",
            "Arabian": "Арабский",
        },
        "countries": {
            "London": "Лондон",
            "New York": "Нью-Йорк",
            "Sydney": "Сидней",
            "Tokyo": "Токио",
            "Moscow": "Москва",
        },
        "enter": "Вход",
        "stillDontHaveAccaunt": "Ещё нет учётной записи?",
        "errors": {
            "errorEmail": "Ошибка ввода e-mail",
            "errorFirstName": "Ошибка ввода имени",
            "errorLastName": "Ошибка ввода фамилии",
        },
        "cellItem": {
            "titleOfBuy": "Покупка",
            "titleOfSell": "Продажа",
            "opencellItem": {
                "diferenceTitle": "Разница:",
                "openTitle": "Открытие:",
                "minTitle": "Мин.:",
                "percentdifereceTitle": "Разница%:",
                "closeTitle": "Закрытие:",
                "maxTitle": "Макс.:",
            },
        },
        "placeHolder": {
            "phoneNumber": "Телефон", "email": "Email", "name": "Имя", "lastName": "Фамилия", "password": "Пароль", "confirmPassword": "Подтверждение пароля"
        },
        "sendBtnText": "Отправить",
        "errorMessage": {
            "phoneNumber": "Неверно указан номер телефона", "email": "Неверный email", "name": "Неверное имя", "lastName": "Неверная фамилия"
        },
        'nameHints': {
            'emptyName': 'Поле обязательно для заполнения',
            'incorrect': 'Введите корректные данные',
            'emptyNameSO': 'Поле обязательно для заполнения',
            'incorrectSO': 'Введите корректные данные',
        },
        'lastNameHints': {
            'emptyName': 'Поле обязательно для заполнения',
            'incorrect': 'Введите корректные данные',
            'emptyNameSO': 'Поле обязательно для заполнения',
            'incorrectSO': 'Введите корректные данные',
        },
        'phoneNumberHints': {
            'emptyName': 'Поле обязательно для заполнения',
            'incorrect': 'Введите правильный номер телефона',
            'onlyNumbers': 'Введите только цифры',
            'emptyNameSO': 'Поле обязательно для заполнения',
            'incorrectSO': 'Введите правильный номер телефона',
            'onlyNumbersSO': 'Введите только цифры',
        },
        'emailHints': {
            'emptyName': 'Поле обязательно для заполнения',
            'incorrect': 'Введите корректный формат эл. почты',
            'symbols': 'Допустимы символы ".", "_", "-", "+", "@"',
            'emptyNameSO': 'Поле обязательно для заполнения',
            'incorrectSO': 'Введите корректный формат эл. почты',
            'symbolsSO': 'Допустимы символы ".", "_", "-", "@"',
        },
        "passwordHints": {
            "emptyName": "Поле обязательно для заполнения",
            "length": "Пароль должен содержать не менее 5 символов",
            "minOneDigit": "В пароле должны присутствовать буквы и цифры",
            "minOneLeter": "В пароле должны присутствовать буквы и цифры",
            "onlyLatinAndDigits": "5-20 знаков, английские буквы и цифры",
            "emptyNameSO": "Поле обязательно для заполнения",
            "lengthSO": "Пароль должен содержать не менее 5 символов",
            "minOneDigitSO": "В пароле должны присутствовать буквы и цифры",
            "minOneLeterSO": "В пароле должны присутствовать буквы и цифры",
            "onlyLatinAndDigitsSO": "5-20 знаков, английские буквы и цифры"
        },
        "confirmPasswordHints": {
            "emptyName": "Поле обязательно для заполнения",
            "length": "Пароль должен содержать не менее 5 символов",
            "minOneDigit": "В пароле должны присутствовать буквы и цифры",
            "minOneLeter": "В пароле должны присутствовать буквы и цифры",
            "onlyLatinAndDigits": "5-20 знаков, английские буквы и цифры",
            "emptyNameSO": "Поле обязательно для заполнения",
            "lengthSO": "Пароль должен содержать не менее 5 символов",
            "minOneDigitSO": "В пароле должны присутствовать буквы и цифры",
            "minOneLeterSO": "В пароле должны присутствовать буквы и цифры",
            "onlyLatinAndDigitsSO": "5-20 знаков, английские буквы и цифры"
        },
        "confirmPasswordMatch": "Пароли должны совпадать",
        "emailExists": "Такой адрес уже существует",
        "statusCodes": {
            "500": "Регистрация недоступна,повторите попытку.",
        },
        "errorTypes": {
            "3": "Слишком простой пароль",
            "6": "Пользователь с этим e-mail уже зарегистрирован."
        },
        "EmailOrPassWrong": "Некорректный адрес электронной почты или пароль",
        "ServerUnreachable": "Ошибка при подключении к серверу",
        "ConnectionError": "Не удалось войти из-за проблем с соединением. Проверьте подключение к Интернету",
        "AnotherProblem": "Обнаружена непредвиденная ошибка",
        "EmailIsExist": "Пользователь с таким e-mail уже существует. Найдите письмо с паролем на вашей почте или зарегистрируйтесь под новым e-mail адресом.",
        "InvalidParameters": "Регистрация в данный момент недоступна. Повторите попытку позже",
        "RegSuccess": "Регистрация прошла успешно",
        "EmailWrong": "Некорректный адрес электронной почты",
        "PasswordRecoverySuccess": "Инструкция по восстановлению пароля отправлена на почту пользователя",
    },
    "en": {
        'noMessage':'No notifications',
        'regPopUp':'Your password has been sent to the specified email address',
        'helpSearch': 'Enter search words',
        'Catalog': 'Catalog',
        'Help': 'Help',
        'Other': 'Other',
        'Favorites': 'Favorites',
        'Glossary': 'Glossary',
        'ContactBroker': 'Contact your broker',
        'OurApps': 'Trading App',
        'OurWebsite': 'Our website',
        'LanguagePreference': 'Language preference',
        'YouLoggedAs': 'You are logged in as ',
        'LogInToTheAccount': 'Log in to the account',
        'ManagerWillContact': 'Manager will contact you shortly',
        'thanks': 'Thank you!',
        "recvOffers":"Get an offer",
        'createAccount': 'Create account',
        'Day': 'day',
        'Week': 'week',
        "Authorization": "Authorization",
        "More news": "More news",
        "Save": "Save",
        "Specification": "Specification",
        "Instruments": "Instruments",
        "Session": "Session",
        "Time": "Time",
        "Home": "Home",
        "Settings": "Settings",
        "News": "News",
        'Buy': 'Buy',
        'Sell': 'Sell',
        'Neutral': 'Neutral',
        'Quote': 'Quote',
        'Indicators': 'Indicators',
        'MovingAverages': 'Moving averages',
        'Hour': 'hour',
        'min': 'min',
        'LastUpdate': 'Last update',
        "Yes": "Yes",
        "No": "No",
        "OK": "OK",
        "Cancel": "Cancel",
        "login": "Log in",
        "turnBtn": "Minimise all",
        "exit": "Logout",
        "notifications": "Notifications",
        "error!": "Error!",
        "signup": "Sign up",
        "signup2": "Sign up",
        "introduced": "Introduced",
        "Country": "Country",
        "Registration": "Registration",
        "Last tool cannot be removed from favorites": "Last tool cannot be removed from favorites",
        "To get full access to the instruments...": "To get full access to the instruments, you need to log in",
        "Are you sure you want to log out?": "Are you sure you want to log out?",
        "Thank you for joining us!": "Thank you\n\r for joining us!",
        "A letter to confirm your data...": "A letter to confirm your data and complete the registration process has been sent to the email you specified",
        "Instructions for password recovery...": "Instructions\n\r for password recovery have been sent to the user's email",
        "Something went wrong": "Something went wrong",
        "Invalid email address or server error": "Invalid email address or server error",
        "Invalid email address or password": "Invalid email address or password",
        "Password recovery": "Password recovery",
        "Please specify the email you used when registering": "Please specify the email you used when registering",
        "Email-entry error": "Email-entry error",
        "Forgot password?": "Forgot password?",
        "Password failed": "Password failed",
        "Already have an account?": "Already have an account?",
        "I have read and agree with": "By submitting this form, I accept",
        "user agreement": "the conditions for processing personal data.",
        "user agreement2": "User agreement",
        "Enter your country": "Enter your country",
        "10 characters minimum": "10 characters minimum",
        "Leave a comment": "Leave a comment",
        "Liked the application":"Liked the application?\nRate it!",
        "Remind me later": "Remind me later",
        "tabbar": {
            "currency": "Currencies",
            "commodity": "Commodities",
            "index": "Indices",
            "stock": "Stocks",
            "home": "Home",
        },
        "Languages": {
            "Russian": "Russian",
            "English": "English",
            "Spanish": "Spanish",
            "Arabian": "Arabian",
        },
        "countries": {
            "London": "London",
            "New York": "New York",
            "Sydney": "Sydney",
            "Tokyo": "Tokyo",
            "Moscow": "Moscow",
        },
        "enter": "Log in",
        "stillDontHaveAccaunt": "Do not have an account yet?",
        "errors": {
            "errorEmail": "Email-entry error",
            "errorFirstName": "Name-entry error",
            "errorLastName": "Last name-entry error",
        },
        "cellItem": {
            "titleOfBuy": "Buy",
            "titleOfSell": "Sell",
            "opencellItem": {
                "diferenceTitle": "Profitablity:",
                "openTitle": "Open:",
                "minTitle": "min.:",
                "percentdifereceTitle": "Profitablity%:",
                "closeTitle": "Close:",
                "maxTitle": "max.:",
            },
        },
        "placeHolder": {
            "phoneNumber": "Phone number",
            "email": "Email",
            "name": "First Name",
            "lastName": "Last Name",
            "password": "Password",
            "confirmPassword": "Confirm password"
        },
        "sendBtnText": "Send",
        "submitButton": "Submit",
        "errorMessage": {
            "phoneNumber": "Invalid phone number",
            "email": "error email",
            "name": "error name",
            "lastName": "error lastName"
        },
        "nameHints": {
            "emptyName": "This field is required",
            "incorrect": "Invalid input",
            "emptyNameSO": "This field is required",
            "incorrectSO": "Invalid input",
            "minLength": "The field may contain between 1 and 200 characters",
            "minLengthSO": "The field may contain between 1 and 45 characters"
        },
        "lastNameHints": {
            "emptyName": "This field is required",
            "incorrect": "Invalid input",
            "emptyNameSO": "This field is required",
            "incorrectSO": "Invalid input",
            "minLength": "The field may contain between 1 and 200 characters",
            "minLengthSO": "The field may contain between 1 and 45 characters"
        },
        "phoneNumberHints": {
            "emptyName": "This field is required",
            "incorrect": "Enter a valid phone number",
            "onlyNumbers": "Please enter only digits",
            "emptyNameSO": "This field is required",
            "incorrectSO": "Enter a valid phone number",
            "onlyNumbersSO": "Please enter only digits",
            "minLength": "The  length minimum of 6 characters",
            "other": "Please enter a valid phone number",
            "minLengthSO": "The  length minimum of 6 characters",
            "onlyNumberSO": "You can only enter the numbers",
            "otherSO": "Please enter a valid phone number"
        },
        "emailHints": {
            "emptyName": "This field is required",
            "incorrect": "Enter a valid email address",
            "symbols": "Characters allowed \".\", \"_\", \"-\", \"+\", \"@\"",
            "emptyNameSO": "This field is required",
            "incorrectSO": "Enter a valid email address",
            "symbolsSO": "Characters allowed \".\", \"_\", \"-\", \"@\"",
            "beforeAt": "Incorrect format of field before @",
            "afterAt": "Incorrect format of field after @",
            "beforeAtSO": "Incorrect format of field before @",
            "afterAtSO": "Incorrect format of field after @"
        },
        "passwordHints": {
            "emptyName": "This field is required",
            "length": "Password must contain at least 5 characters",
            "minOneDigit": "Password must contain letters and numbers",
            "minOneLeter": "Password must contain letters and numbers",
            "onlyLatinAndDigits": "5-20 characters, English letters and numbers",
            "emptyNameSO": "This field is required",
            "lengthSO": "Password must contain at least 5 characters",
            "minOneDigitSO": "Password must contain letters and numbers",
            "minOneLeterSO": "Password must contain letters and numbers",
            "onlyLatinAndDigitsSO": "5-20 characters, English letters and numbers"
        },
        "confirmPasswordHints": {
            "emptyName": "This field is required",
            "length": "Password must contain at least 5 characters",
            "minOneDigit": "Password must contain letters and numbers",
            "minOneLeter": "Password must contain letters and numbers",
            "onlyLatinAndDigits": "5-20 characters, English letters and numbers",
            "emptyNameSO": "This field is required",
            "lengthSO": "Password must contain at least 5 characters",
            "minOneDigitSO": "Password must contain letters and numbers",
            "minOneLeterSO": "Password must contain letters and numbers",
            "onlyLatinAndDigitsSO": "5-20 characters, English letters and numbers"
        },
        "confirmPasswordMatch": "Passwords must match",
        "emailExists": "This email already exists",
        "statusCodes": {
            "500": "Registration failed. Try again later."
        },
        "errorTypes": {
            "3": "The password is too simple",
            "6": "This email already exists"
        },
        "EmailOrPassWrong": "Incorrect email address or password.",
        "ServerUnreachable": "An error occurred while connecting to the server.",
        "ConnectionError": "Unable to log in due to problems with a network. Please check your internet connetion.",
        "AnotherProblem": "An unexpected error has occured.",
        "EmailIsExist": "A user with this email already exists. Please find a letter with a password in your mailbox or register using a new email address.",
        "InvalidParameters": "Registration is currently unavailable. Try again later",
        "RegSuccess": "Registration completed successfully!",
        "EmailWrong": "Incorrect email address.",
        "PasswordRecoverySuccess": "Password recovery guide was sent to the users email.",
    },
    "es": {
        'noMessage':'No Notificaciones',
        'regPopUp':'Su contraseña ha sido enviada al correo electrónico especificado',
        'helpSearch': 'Ingresa palabras de búsqueda',
        'Catalog': 'Catálogo',
        'Help': 'Ayuda',
        'Other': 'Otros',
        'Favorites': 'Favoritos',
        'Glossary': 'Diccionario',
        'ContactBroker': 'Póngase en contacto con su agente',
        'OurApps': 'Aplicación de trading',
        'OurWebsite': 'Nuestro sitio',
        'LanguagePreference': 'Selección de idioma',
        'YouLoggedAs': 'Has iniciado sesión como ',
        'LogInToTheAccount': 'Iniciar sesión en la cuenta',
        'ManagerWillContact': 'El gerente se pondrá en contacto con usted pronto.',
        'thanks': 'Muchas gracias',
        "recvOffers": "Obtener una oferta",
        'createAccount': 'Crear una cuenta',
        'Day': 'día',
        'Week': 'semana',
        "Authorization": "Autorización",
        "More news": "Mas noticias",
        "Save": "Guardar",
        "Specification": "Detalles",
        "Instruments": "Herramientas",
        "Session": "Sesion",
        "Time": "Tiempo",
        "Home": "Inicio",
        "Settings": "Ajustes",
        "News": "Noticias",
        'Buy': 'Comprar',
        'Sell': 'Vender',
        'Neutral': 'Neutral',
        'Quote': 'Cita',
        'Indicators': 'Indicadores',
        'MovingAverages': 'Promedios moviles',
        'Hour': 'hora',
        'min': 'min',
        'LastUpdate': 'Ultima actualización',
        "Yes": "Sí",
        "No": "No",
        "OK": "OK",
        "Cancel": "Cancelar",
        "login": "Iniciar sesión",
        "turnBtn": "Colapsar todo",
        "exit": "Salir",
        "notifications": "Notificaciones",
        "error!": "Error!",
        "signup": "Registrarse",
        "signup2": "Registrarse",
        "introduced": "Introducido",
        "Country": "País",
        "Registration": "Registro",
        "Last tool cannot be removed from favorites": "La última herramienta no se puede eliminar de favoritos",
        "To get full access to the instruments...": "Para tener acceso completo a las herramientas, debe iniciar sesión",
        "Are you sure you want to log out?": "Estás seguro de que quieres dejarlo?",
        "Thank you for joining us!": "¡Gracias\n\r por unirte a nosotros!",
        "A letter to confirm your data...": "Se envió una carta para confirmar sus datos y completar el proceso de registro al correo electrónico indicado",
        "Instructions for password recovery...": "Instrucciones\n\r para recuperar la contraseña enviadas al correo del usuario",
        "Something went wrong": "algo salió mal",
        "Invalid email address or server error": "Dirección de correo electrónico no válida o error del servidor",
        "Invalid email address or password": "Dirección de correo electrónico o contraseña inválida",
        "Password recovery": "Recuperación de contraseña",
        "Please specify the email you used when registering": "Indique el correo electrónico que usó al registrarse",
        "Email-entry error": "Error al ingresar el correo electrónico",
        "Forgot password?": "¿Se te olvidó tu contraseña?",
        "Password failed": "Contraseña fallida",
        "Already have an account?": "Ya tienes una cuenta?",
        "I have read and agree with": "Al completar el formulario de registro, yo acepto ",
        "user agreement": "las condiciones para procesar los datos personales.",
        "user agreement2": "Acuerdo de usuario",
        "Enter your country": "Ingrese su país",
        "10 characters minimum": "Número mínimo de 10 caracteres ",
        "Leave a comment": "Número mínimo de 10 caracteres ",
        "Liked the application": "Me gusta la aplicación?\n¡Aprecio!",
        "Remind me later": "Recuérdame más tarde",
        "tabbar": {
            "currency": "Moneda",
            "commodity": "Producto",
            "index": "Índices",
            "stock": "Promociones",
            "home": "Inicio"
        },
        "Languages": {
            "Russian": "Ruso",
            "English": "Inglés",
            "Spanish": "Español",
            "Arabian": "Arabe",
        },
        "countries": {
            "London": "Londres",
            "New York": "Nueva York",
            "Sydney": "Sidney",
            "Tokyo": "Tokyo",
            "Moscow": "Moscú",
        },
        "enter": "Iniciar sesión",
        "stillDontHaveAccaunt": "¿Aún no tienes una cuenta?",
        "errors": {
            "errorEmail": "Error al ingresar el correo electrónico",
            "errorFirstName": "Error al ingresar el nombre",
            "errorLastName": "Error al escribir un apellido",
        },
        "cellItem": {
            "titleOfBuy": "Comprando",
            "titleOfSell": "Vender",
            "opencellItem": {
                "diferenceTitle": "Diferencia:",
                "openTitle": "Descubrimiento:",
                "minTitle": "Mínimo:",
                "percentdifereceTitle": "Diferencia%:",
                "closeTitle": "Cerrar:",
                "maxTitle": "Máximo:",
            },
        },
        "placeHolder": {
            "phoneNumber": "Móvil",
            "email": "Email",
            "name": "Nombre de usuario",
            "lastName": "Apellido",
            "password": "Contraseña",
            "confirmPassword": "Confirmar Contraseña"
        },
        "sendBtnText": "Enviar",
        "errorMessage": {
            "phoneNumber": "Número de teléfono inválido",
            "email": "eraro retpoŝto",
            "name": "eraran nomon",
            "lastName": "eraro lasta nomo"
        },
        "nameHints": {
            "emptyName": "Campo requerido",
            "incorrect": "Entrada inválida",
            "emptyNameSO": "Campo requerido",
            "incorrectSO": "Entrada inválida",
            "minLength": "El campo puede contener entre 1 y 200 simbolos",
            "minLengthSO": "El campo puede contener entre 1 y 45 simbolos"
        },
        "lastNameHints": {
            "emptyName": "Campo requerido",
            "incorrect": "Entrada inválida",
            "emptyNameSO": "Campo requerido",
            "incorrectSO": "Entrada inválida",
            "minLength": "El campo puede contener entre 1 y 200 simbolos",
            "minLengthSO": "El campo puede contener entre 1 y 45 simbolos"
        },
        "phoneNumberHints": {
            "emptyName": "Campo requerido",
            "incorrect": "Ingrese un número de teléfono válido",
            "onlyNumbers": "Este campo contiene sólo números",
            "emptyNameSO": "Campo requerido",
            "incorrectSO": "Ingrese un número de teléfono válido",
            "onlyNumbersSO": "Este campo contiene sólo números",
            "minLength": "La longitud mínima de 6 caracteres",
            "other": "Ingrese un número de teléfono válido",
            "minLengthSO": "La longitud mínima de 6 caracteres",
            "onlyNumberSO": "Sólo puede escribir los números",
            "otherSO": "Ingrese un número de teléfono válido"
        },
        "emailHints": {
            "emptyName": "Campo requerido",
            "incorrect": "Introduzca un correo electrónico válido",
            "symbols": "Caracteres permitidos \".\", \"_\", \"-\", \"+\", \"@\"",
            "emptyNameSO": "Campo requerido",
            "incorrectSO": "Introduzca un correo electrónico válido",
            "symbolsSO": "Caracteres permitidos \".\", \"_\", \"-\", \"@\"",
            "beforeAt": "ES Incorrect format of field before @",
            "afterAt": "ES Incorrect format of field after @",
            "beforeAtSO": "ES Incorrect format of field before @",
            "afterAtSO": "ES Incorrect format of field after @"
        },
        "passwordHints": {
            "emptyName": "Campo requerido",
            "length": "La contraseña debe contener al menos 5 caracteres",
            "minOneDigit": "La contraseña debe contener letras y números",
            "minOneLeter": "La contraseña debe contener letras y números",
            "onlyLatinAndDigits": "5-20 caracteres, letras y números en inglés",
            "emptyNameSO": "Campo requerido",
            "lengthSO": "La contraseña debe contener al menos 5 caracteres",
            "minOneDigitSO": "La contraseña debe contener letras y números",
            "minOneLeterSO": "La contraseña debe contener letras y números",
            "onlyLatinAndDigitsSO": "5-20 caracteres, letras y números en inglés"
        },
        "confirmPasswordHints": {
            "emptyName": "Campo requerido",
            "length": "La contraseña debe contener al menos 5 caracteres",
            "minOneDigit": "La contraseña debe contener letras y números",
            "minOneLeter": "La contraseña debe contener letras y números",
            "onlyLatinAndDigits": "5-20 caracteres, letras y números en inglés",
            "emptyNameSO": "This field is required",
            "lengthSO": "La contraseña debe contener al menos 5 caracteres",
            "minOneDigitSO": "La contraseña debe contener letras y números",
            "minOneLeterSO": "La contraseña debe contener letras y números",
            "onlyLatinAndDigitsSO": "5-20 caracteres, letras y números en inglés"
        },
        "confirmPasswordMatch": "Las contraseñas deben coincidir",
        "emailExists": "Este correo electrónico ya existe",
        "statusCodes": {
            "500": "Registración fallida. Vuelva más tarde"
        },
        "errorTypes": {
            "3": "The password is too simple",
            "6": "Este correo electrónico ya existe"
        },
        "EmailOrPassWrong": "Incorrecta la dirección de correo electrónico o la contraseña",
        "ServerUnreachable": "Ocurrió un error al conectarse con el servidor",
        "ConnectionError": "No se puede iniciar sesión debido a problemas con la red. Por favor revisa tu conexión a internet",
        "AnotherProblem": "Ocurrió un error inesperado",
        "EmailIsExist": "Ya existe un usuario con este correo electrónico. Encuentre una carta con su contraseña en su correo o regístrese con una nueva dirección de correo electrónico",
        "InvalidParameters": "El registro no está disponible actualmente. Inténtentelo de nuevo más tarde",
        "RegSuccess": "Registro completado con éxito!",
        "EmailWrong": "Dirección de Correo electrónico incorrecto.",
        "PasswordRecoverySuccess": "Se envió una guía de recuperación de contraseñas al correo electrónico de los usuarios",
    },
    "ar": {
        'noMessage':'لا يوجد إعلام',
        'regPopUp':'تم إرسال كلمة المرور إلى البريد الإلكتروني المحدد',
        'helpSearch': 'أدخل كلمات البحث',
        'Catalog': 'دليل',
        'Help': 'مساعدة',
        'Other': 'أخرى',
        'Favorites': 'المفضلة',
        'Glossary': 'قاموس',
        'ContactBroker': 'التواصل مع وسيط',
        'OurApps': 'تطبيق التداول',
        'OurWebsite': 'موقعنا',
        'LanguagePreference': 'اختيار اللغة',
        'YouLoggedAs': ' قمت بتسجيل الدخول باسم ',
        'LogInToTheAccount': 'تسجيل الدخول إلى الحساب',
        'ManagerWillContact': 'سيقوم المدير بالاتصال بك قريبا',
        'thanks': 'شكراً!',
        "recvOffers": "أحصل على التطبيق",
        'createAccount': 'انشاء حساب',
        'Day': 'يوم',
        'Week': 'أسبوع',
        "Authorization": "تفويض",
        "More news": "المزيد من الأخبار",
        "Save": "حفظ",
        "Specification": "التفاصيل",
        "Instruments": "الأدوات",
        "Session": "دورة",
        "Time": "التوقيت",
        "Home": "الصفحة الرئيسية",
        "Settings": "الإعدادات",
        "News": "الأخبار",
        'Buy': 'شراء',
        'Sell': 'بيع',
        'Neutral': 'محايد',
        'Quote': 'اقتباس',
        'Indicators': 'مؤشرات',
        'MovingAverages': 'المتوسطات المتحركة',
        'Hour': 'ساعة',
        'min': 'دقيقة',
        'LastUpdate': 'آخر تحديث',
        "Yes": "نعم",
        "No": "لا",
        "OK": "حسنا",
        "Cancel": "إلغاء",
        "login": "دخول",
        "turnBtn": "طي الكل",
        "exit": "خروج",
        "notifications": "إشعار",
        "error!": "!خطأ",
        "signup": "تسجيل",
        "signup2": "تسجيل",
        "introduced": "مألوف",
        "Country": "الدولة",
        "Registration": "استمارة التسجيل",
        "Last tool cannot be removed from favorites": "يستحيل حذف الصك الأخير من لائحة المفضلات",
        "To get full access to the instruments...": "للحصول على حق الوصول الكامل إلى الأدوات، تحتاج إلى تسجيل الدخول",
        "Are you sure you want to log out?": "هل أنت متأكد من أنك تريد تسجيل الدخول؟",
        "Thank you for joining us!": "شكرا لانضمامك إلينا!",
        "A letter to confirm your data...": "تم إرسال خطاب لتأكيد البيانات الخاصة بك وإكمال عملية التسجيل إلى البريد الإلكتروني المشار إليه",
        "Instructions for password recovery...": "تعليمات لاستعادة كلمة المرور المرسلة إلى بريد المستخدم",
        "Something went wrong": "شيء ما خطأ",
        "Invalid email address or server error": "عنوان بريد إلكتروني غير صالح أو خطأ في الخادم",
        "Invalid email address or password": "عنوان بريد إلكتروني أو كلمة مرور غير صالحة",
        "Password recovery": "استعادة كلمة المرور",
        "Please specify the email you used when registering": "يرجى توضيح البريد الإلكتروني الذي استخدمته عند التسجيل",
        "Email-entry error": "خطأ في إدخال البريد الإلكتروني",
        "Forgot password?": "هل نسيت كلمة المرور؟",
        "Password failed": "فشل كلمة المرور",
        "Already have an account?": "لديك بالفعل حساب؟",
        "I have read and agree with": "بملئ استمارة التسجيل، أوافق على",
        "user agreement": "شروط معالجة المعلومات الشخصية",
        "user agreement2": "اتفاق المستخدم",
        "Enter your country": "تحديد البلد",
        "10 characters minimum": "الحد الأدنى لعدد الرموز هو 10",
        "Leave a comment": "الحد الأدنى لعدد الرموز هو 10",
        "Liked the application": "أحببت التطبيق؟\n تقييم التطبيق!" ,
        "Remind me later": "ذكرني لاحقا",
        "tabbar": {
            "currency": "العملات",
            "commodity": "السلع",
            "index": "مؤشرات",
            "stock": "أسهم",
            "home": "الصفحة الرئيسية",
        },
        "Languages": {
            "Russian": "الروسية",
            "English": "الإنجليزية",
            "Spanish": "الأسبانية",
            "Arabian": "العربية",
        },
        "countries": {
            "London": "لندن",
            "New York": "نيويورك",
            "Sydney": "سيدني",
            "Tokyo": "طوكيو",
            "Moscow": "موسكو",
        },
        "enter": "تسجيل الدخول",
        "stillDontHaveAccaunt": "ليس لديك حساب حتى الآن؟",
        "errors": {
            "errorEmail": "خطأ في إدخال البريد الإلكتروني",
            "errorFirstName": "خطأ في إدخال الاسم",
            "errorLastName": "خطأ في كتابة اسم العائلة",
        },
        "cellItem": {
            "titleOfBuy": "شراء",
            "titleOfSell": "بيع",
            "opencellItem": {
                "diferenceTitle": ":الربحية",
                "openTitle": ":اكتشاف",
                "minTitle": ":الحد الأدنى",
                "percentdifereceTitle": ":%الربحية",
                "closeTitle": ":غلق",
                "maxTitle": ":الحد الأقصى",
            },
        },
        "placeHolder": {
            "phoneNumber": "الهاتف",
            "email": "البريد الإكتروني",
            "name": "الإسم",
            "lastName": "الإسم العائلي",
            "password": "كلمة السر",
            "confirmPassword": "تأكيد كلمة المرور"
        },
        "sendBtnText": "لإرسال",
        "errorMessage": {
            "phoneNumber": "رقم الهاتف غير صالح",
            "email": "البريد الإلكتروني خطأ",
            "name": "الاسم خطأ",
            "lastName": "اسم العائلة خطأ"
        },
        "nameHints": {
            "emptyName": "هذا الحقل مطلوب",
            "incorrect": "ادخال غير صالح",
            "emptyNameSO": "هذا الحقل مطلوب",
            "incorrectSO": "ادخال غير صالح",
            "minLength": "هذا الحقل يجب أن يحتوي من ١ إلى ٢٠٠ رم",
            "minLengthSO": "هذا الحقل يجب أن يحتوي من ١ إلى ٢٠٠ رم"
        },
        "lastNameHints": {
            "emptyName": "هذا الحقل مطلوب",
            "incorrect": "ادخال غير صالح",
            "emptyNameSO": "هذا الحقل مطلوب",
            "incorrectSO": "ادخال غير صالح",
            "minLength": "هذا الحقل يجب أن يحتوي من ١ إلى ٢٠٠ رم",
            "minLengthSO": "هذا الحقل يجب أن يحتوي من ١ إلى ٢٠٠ رم"
        },
        "phoneNumberHints": {
            "emptyName": "هذا الحقل مطلوب",
            "incorrect": "إدخل رقم هاتف صالح",
            "onlyNumbers": " يرجى استخدام أرقام فقط",
            "emptyNameSO": "هذا الحقل مطلوب",
            "incorrectSO": "إدخل رقم هاتف صالح",
            "onlyNumbersSO": " يرجى استخدام أرقام فقط",
            "minLength": "الحد الأدنى للطول 6 أحرف",
            "other": "أدخل رقم هاتف صالح",
            "minLengthSO": "الحد الأدنى للطول 6 أحرف",
            "onlyNumberSO": "يمكنك إدخال أرقام فقط",
            "otherSO": "أدخل رقم هاتف صالح"
        },
        "emailHints": {
            "emptyName": "هذا الحقل مطلوب",
            "incorrect": "أدخل عنوان بريد إلكتروني صالح",
            "symbols": "\".\", \"_\", \"-\", \"+\", \"@\" مسموح ادخال احرف خاصة",
            "emptyNameSO": "هذا الحقل مطلوب",
            "incorrectSO": "أدخل عنوان بريد إلكتروني صالح",
            "symbolsSO": "\".\", \"_\", \"-\", \"@\" مسموح ادخال احرف خاصة",
            "beforeAt": "AR Incorrect format of field before @",
            "afterAt": "AR Incorrect format of field after @",
            "beforeAtSO": "AR Incorrect format of field before @",
            "afterAtSO": "AR Incorrect format of field after @"
        },
        "passwordHints": {
            "emptyName": "يجب ملأ الفراغ",
            "length": "كلمة السر يجب ان تحتوي على أكثر من 5 رموز",
            "minOneDigit": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "minOneLeter": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "onlyLatinAndDigits": "5-20رمز, حروف انجليزية و أرقام",
            "emptyNameSO": "يجب ملأ الفراغ",
            "lengthSO": "كلمة السر يجب ان تحتوي على أكثر من 5 رموز",
            "minOneDigitSO": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "minOneLeterSO": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "onlyLatinAndDigitsSO": " 5-20رمز, حروف انجليزية و أرقام"
        },
        "confirmPasswordHints": {
            "emptyName": "يجب ملأ الفراغ",
            "length": "كلمة السر يجب ان تحتوي على أكثر من 5 رموز",
            "minOneDigit": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "minOneLeter": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "onlyLatinAndDigits": "5-20 رمز, حروف انجليزية و أرقام",
            "emptyNameSO": "يجب ملأ الفراغ",
            "lengthSO": "كلمة السر يجب ان تحتوي على أكثر من 5 رموز",
            "minOneDigitSO": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "minOneLeterSO": "كلمة السر يجب أن تحتوي على أرقام و حروف",
            "onlyLatinAndDigitsSO": "5-20رمز, حروف انجليزية و أرقام"
        },
        "confirmPasswordMatch": "كلمات السر يجب أن تتطابق مع بعضها",
        "emailExists": "هذا البريد الإلكتروني موجود مسبقا",
        "statusCodes": {
            "500": ".التسجيل غير ممكن. أعد المحاولة لاحقا"
        },
        "errorTypes": {
            "3": "The password is too simple",
            "6": "هذا البريد الإلكتروني موجود مسبقا"
        },
        "EmailOrPassWrong": "عنوان بريد إلكتروني أو كلمة مرور غير صالحة",
        "ServerUnreachable": "حدث خطأ أثناء الاتصال بالخادم",
        "ConnectionError": "لا يمكن تسجيل الدخول بسبب مشاكل في الشبكة. يرجى التحقق من اتصال الإنترنت الخاص بك",
        "AnotherProblem": "حدث خطأ غير متوقع",
        "EmailIsExist": "البريد الإلكتروني هذا تم استعماله من قبل. قم بالبحث عن رسالة مع كلمة السر في بريدك الإلكتروني أو قم بالتسجيل ببريد إلكتروني اخر.",
        "InvalidParameters": "التسجيل في الوقت الحالي غير ممكن. أعد المحاولة في وقت لاحق",
        "RegSuccess": "انتهى التسجيل بنجاح",
        "EmailWrong": "عنوان بريد إلكتروني غير صالح",
        "PasswordRecoverySuccess": "تم إرسال دليل استرداد كلمة المرور إلى عنوان البريد الإلكتروني المستخدم",
    }
}