export const countriesru = {
    "AU": { "phcode": "61", "countryName": "Австралия" },
    "AT": { "phcode": "43", "countryName": "Австрия" },
    "AZ": { "phcode": "994", "countryName": "Азербайджан" },
    "AX": { "phcode": "3581", "countryName": "Аландские острова" },
    "AL": { "phcode": "355", "countryName": "Албания" },
    "DZ": { "phcode": "213", "countryName": "Алжир" },
    "VI": { "phcode": "1340", "countryName": "Американские Виргинские острова" },
    "AS": { "phcode": "1684", "countryName": "Американские Самоа" },
    "AI": { "phcode": "1264", "countryName": "Ангилья" },
    "AO": { "phcode": "244", "countryName": "Ангола" },
    "AD": { "phcode": "376", "countryName": "Андорра" },
    "AQ": { "phcode": "672", "countryName": "Антарктика" },
    "AG": { "phcode": "1268", "countryName": "Антигуа и Барбуда" },
    "AN": { "phcode": "599", "countryName": "Антильские острова" },
    "AR": { "phcode": "54", "countryName": "Аргентина" },
    "AM": { "phcode": "374", "countryName": "Армения" },
    "AW": { "phcode": "297", "countryName": "Аруба" },
    "AF": { "phcode": "93", "countryName": "Афганистан" },
    "BS": { "phcode": "1242", "countryName": "Багамы" },
    "BD": { "phcode": "880", "countryName": "Бангладеш" },
    "BB": { "phcode": "1246", "countryName": "Барбадос" },
    "BH": { "phcode": "973", "countryName": "Бахрейн" },
    "BY": { "phcode": "375", "countryName": "Беларусь" },
    "BZ": { "phcode": "501", "countryName": "Белиз" },
    "BE": { "phcode": "32", "countryName": "Бельгия" },
    "BJ": { "phcode": "229", "countryName": "Бенин" },
    "BM": { "phcode": "1441", "countryName": "Бермуды" },
    "BG": { "phcode": "359", "countryName": "Болгария" },
    "BO": { "phcode": "591", "countryName": "Боливия" },
    "BA": { "phcode": "387", "countryName": "Босния и Герцеговина" },
    "BW": { "phcode": "267", "countryName": "Ботсвана" },
    "BR": { "phcode": "55", "countryName": "Бразилия" },
    "IO": { "phcode": "246", "countryName": "Британская территория в Индийском океане" },
    "VG": { "phcode": "1284", "countryName": "Британские Виргинские острова" },
    "BN": { "phcode": "673", "countryName": "Бруней-Даруссалам" },
    "BV": { "phcode": "47", "countryName": "Буве" },
    "BF": { "phcode": "226", "countryName": "Буркина Фасо" },
    "BI": { "phcode": "257", "countryName": "Бурунди" },
    "BT": { "phcode": "975", "countryName": "Бутан" },
    "VU": { "phcode": "678", "countryName": "Вануату" },
    "VA": { "phcode": "379", "countryName": "Ватикан" },
    "GB": { "phcode": "44", "countryName": "Великобритания" },
    "HU": { "phcode": "36", "countryName": "Венгрия" },
    "VE": { "phcode": "58", "countryName": "Венесуэла" },
    // "TP": { "phcode": "670", "countryName": "Восточный Тимор" },
    "VN": { "phcode": "84", "countryName": "Вьетнам" },
    "GA": { "phcode": "241", "countryName": "Габон" },
    "HT": { "phcode": "509", "countryName": "Гаити" },
    "GY": { "phcode": "592", "countryName": "Гайана" },
    "GM": { "phcode": "220", "countryName": "Гамбия" },
    "GH": { "phcode": "233", "countryName": "Гана" },
    "GP": { "phcode": "590", "countryName": "Гваделупе" },
    "GT": { "phcode": "502", "countryName": "Гватемале" },
    "GN": { "phcode": "224", "countryName": "Гвинея" },
    "GW": { "phcode": "245", "countryName": "Гвинея-Биссау" },
    "DE": { "phcode": "49", "countryName": "Германия" },
    "GG": { "phcode": "4414", "countryName": "Гернси" },
    "GI": { "phcode": "350", "countryName": "Гибралтар" },
    "HN": { "phcode": "504", "countryName": "Гондурас" },
    "HK": { "phcode": "852", "countryName": "Гонконг" },
    "GD": { "phcode": "1473", "countryName": "Гренада" },
    "GL": { "phcode": "299", "countryName": "Гренландия" },
    "GR": { "phcode": "30", "countryName": "Греция" },
    "GE": { "phcode": "995", "countryName": "Грузия" },
    "GU": { "phcode": "1671", "countryName": "Гуам" },
    "DK": { "phcode": "45", "countryName": "Дания" },
    "CD": { "phcode": "242", "countryName": "Демократическая Республика Конго" },
    "JE": { "phcode": "4415", "countryName": "Джерси" },
    "DJ": { "phcode": "253", "countryName": "Джибути" },
    "DM": { "phcode": "1767", "countryName": "Доминикана" },
    "DO": { "phcode": "1809", "countryName": "Доминиканская Республика" },
    "EG": { "phcode": "20", "countryName": "Египет" },
    "ZM": { "phcode": "260", "countryName": "Замбия" },
    "EH": { "phcode": "212", "countryName": "Западная Сахара" },
    "ZW": { "phcode": "263", "countryName": "Зимбабве" },
    // "IL": { "phcode": "972", "countryName": "Израиль" },
    "IN": { "phcode": "91", "countryName": "Индия" },
    "ID": { "phcode": "62", "countryName": "Индонезия" },
    "JO": { "phcode": "962", "countryName": "Иордания" },
    "IQ": { "phcode": "964", "countryName": "Ирак" },
    "IR": { "phcode": "98", "countryName": "Иран" },
    // "IE": { "phcode": "353", "countryName": "Ирландия" },
    "IS": { "phcode": "354", "countryName": "Исландия" },
    "ES": { "phcode": "34", "countryName": "Испания" },
    "IT": { "phcode": "39", "countryName": "Италия" },
    "YE": { "phcode": "967", "countryName": "Йемен" },
    "CV": { "phcode": "238", "countryName": "Кабо-Верде" },
    "KZ": { "phcode": "7", "countryName": "Казахстан" },
    "KY": { "phcode": "1345", "countryName": "Каймановы острова" },
    "KH": { "phcode": "855", "countryName": "Камбоджа" },
    "CM": { "phcode": "237", "countryName": "Камерун" },
    // "CA": { "phcode": "1", "countryName": "Канада" },
    "QA": { "phcode": "974", "countryName": "Катар" },
    "KE": { "phcode": "254", "countryName": "Кения" },
    "CY": { "phcode": "357", "countryName": "Кипр" },
    "KG": { "phcode": "996", "countryName": "Киргизстан" },
    "KI": { "phcode": "686", "countryName": "Кирибати" },
    "CN": { "phcode": "86", "countryName": "Китай" },
    "CC": { "phcode": "61", "countryName": "Кокосовые острова (Килинг)" },
    "CO": { "phcode": "57", "countryName": "Колумбия" },
    "KM": { "phcode": "269", "countryName": "Коморские Острова" },
    "CG": { "phcode": "242", "countryName": "Конго" },
    // "KV": { "phcode": "383", "countryName": "Косово" },
    "CR": { "phcode": "506", "countryName": "Коста-Рика" },
    "CI": { "phcode": "225", "countryName": "Кот-д`Ивуар" },
    "CU": { "phcode": "53", "countryName": "Куба" },
    "KW": { "phcode": "965", "countryName": "Кувейт" },
    "LA": { "phcode": "856", "countryName": "Лаос" },
    "LV": { "phcode": "371", "countryName": "Латвия" },
    "LS": { "phcode": "266", "countryName": "Лесото" },
    "LR": { "phcode": "231", "countryName": "Либерия" },
    "LB": { "phcode": "961", "countryName": "Ливан" },
    "LY": { "phcode": "218", "countryName": "Ливия" },
    "LT": { "phcode": "370", "countryName": "Литва" },
    "LI": { "phcode": "423", "countryName": "Лихтенштейн" },
    "LU": { "phcode": "352", "countryName": "Люксембург" },
    "MR": { "phcode": "222", "countryName": "Мавритания" },
    "MG": { "phcode": "261", "countryName": "Мадагаскар" },
    "YT": { "phcode": "262", "countryName": "Майотта" },
    "MO": { "phcode": "853", "countryName": "Макао" },
    "MK": { "phcode": "389", "countryName": "Македония" },
    "MW": { "phcode": "265", "countryName": "Малави" },
    "MY": { "phcode": "60", "countryName": "Малайзия" },
    "ML": { "phcode": "223", "countryName": "Мали" },
    "MV": { "phcode": "960", "countryName": "Мальдивы" },
    "MT": { "phcode": "356", "countryName": "Мальта" },
    "MQ": { "phcode": "596", "countryName": "Мартиника" },
    "MH": { "phcode": "692", "countryName": "Маршалловы Острова" },
    "MX": { "phcode": "52", "countryName": "Мексика" },
    "FM": { "phcode": "691", "countryName": "Микронезия" },
    "MZ": { "phcode": "258", "countryName": "Мозамбик" },
    "MD": { "phcode": "373", "countryName": "Молдова" },
    "MC": { "phcode": "377", "countryName": "Монако" },
    "MN": { "phcode": "976", "countryName": "Монголия" },
    "MS": { "phcode": "1664", "countryName": "Монтсеррат" },
    "MA": { "phcode": "212", "countryName": "Морокко" },
    "MM": { "phcode": "95", "countryName": "Мьянма" },
    "NA": { "phcode": "264", "countryName": "Намибия" },
    "NR": { "phcode": "674", "countryName": "Науру" },
    "NP": { "phcode": "977", "countryName": "Непал" },
    "NE": { "phcode": "227", "countryName": "Нигер" },
    "NG": { "phcode": "234", "countryName": "Нигерия" },
    "NL": { "phcode": "31", "countryName": "Нидерланды" },
    "NI": { "phcode": "505", "countryName": "Никарагуа" },
    "NU": { "phcode": "683", "countryName": "Ниуэ" },
    "NZ": { "phcode": "64", "countryName": "Новая Зеландия" },
    "NC": { "phcode": "687", "countryName": "Новая Каледония" },
    "NO": { "phcode": "47", "countryName": "Норвегия" },
    "AE": { "phcode": "971", "countryName": "Объединенные Арабские Эмираты" },
    "OM": { "phcode": "968", "countryName": "Оман" },
    "MU": { "phcode": "230", "countryName": "Остров Маврикий" },
    "IM": { "phcode": "44", "countryName": "Остров Мэн" },
    "NF": { "phcode": "672", "countryName": "Остров Норфолк" },
    "CX": { "phcode": "61", "countryName": "Остров Рождества" },
    "CK": { "phcode": "682", "countryName": "Острова Кука" },
    "HM": { "phcode": "672", "countryName": "Острова Херд и Макдональд" },
    "PK": { "phcode": "92", "countryName": "Пакистан" },
    "PW": { "phcode": "680", "countryName": "Палау" },
    "PS": { "phcode": "970", "countryName": "Палестина" },
    "PA": { "phcode": "507", "countryName": "Панама" },
    "PG": { "phcode": "675", "countryName": "Папуа Новая Гвинея" },
    "PY": { "phcode": "595", "countryName": "Парагвай" },
    "PE": { "phcode": "51", "countryName": "Перу" },
    "PN": { "phcode": "64", "countryName": "Питкэрн" },
    "PL": { "phcode": "48", "countryName": "Польша" },
    "PT": { "phcode": "351", "countryName": "Португалия" },
    // "PR": { "phcode": "1787", "countryName": "Пуэрто-Рико" },
    "RE": { "phcode": "262", "countryName": "Реюньон" },
    "RU": { "phcode": "7", "countryName": "Российская Федерация" },
    "RW": { "phcode": "250", "countryName": "Руанда" },
    "RO": { "phcode": "40", "countryName": "Румыния" },
    "SV": { "phcode": "503", "countryName": "Сальвадор" },
    "WS": { "phcode": "685", "countryName": "Самоа" },
    "SM": { "phcode": "378", "countryName": "Сан-Марино" },
    "ST": { "phcode": "239", "countryName": "Сан-Томе и Принсипи" },
    "BL": { "phcode": "590", "countryName": "Санкт-Бартельми" },
    "SA": { "phcode": "966", "countryName": "Саудовская Аравия" },
    "SZ": { "phcode": "268", "countryName": "Свазиленд" },
    "SJ": { "phcode": "47", "countryName": "Свалбард и Жан Майен" },
    "SH": { "phcode": "290", "countryName": "Святая Елена" },
    "MF": { "phcode": "590", "countryName": "Святой Мартин" },
    "KP": { "phcode": "850", "countryName": "Северная Корея" },
    "MP": { "phcode": "1670", "countryName": "Северные Марианские острова" },
    "SC": { "phcode": "248", "countryName": "Сейшеллы" },
    "PM": { "phcode": "508", "countryName": "Сен-Пьер и Микелон" },
    "SN": { "phcode": "221", "countryName": "Сенегал" },
    "VC": { "phcode": "1784", "countryName": "Сент-Винсент и Гренадины" },
    "KN": { "phcode": "1758", "countryName": "Сент-Китс и Невис" },
    "LC": { "phcode": "1758", "countryName": "Сент-Люсии" },
    "RS": { "phcode": "381", "countryName": "Сербия" },
    "SG": { "phcode": "65", "countryName": "Сингапур" },
    "SY": { "phcode": "963", "countryName": "Сирия" },
    "SK": { "phcode": "421", "countryName": "Словакия" },
    "SI": { "phcode": "386", "countryName": "Словения" },
    "SB": { "phcode": "677", "countryName": "Соломоновы острова" },
    "SO": { "phcode": "252", "countryName": "Сомали" },
    "SD": { "phcode": "249", "countryName": "Судан" },
    "SR": { "phcode": "597", "countryName": "Суринам" },
    //  "US": { "phcode": "1", "countryName": "США" },
    // "UM": { "phcode": "699", "countryName": "США Внешние малые острова" },
    "SL": { "phcode": "232", "countryName": "Сьерра Лион" },
    "TJ": { "phcode": "992", "countryName": "Таджикистан" },
    "TH": { "phcode": "66", "countryName": "Таиланд" },
    "TW": { "phcode": "886", "countryName": "Тайвань" },
    "TZ": { "phcode": "255", "countryName": "Танзания" },
    "TC": { "phcode": "1649", "countryName": "Теркс и Кайкос" },
    /* "TL": { "phcode": "670", "countryName": "Тимор-Лешти" }, */
    "TG": { "phcode": "228", "countryName": "Того" },
    "TK": { "phcode": "690", "countryName": "Токелау" },
    "TO": { "phcode": "676", "countryName": "Тонга" },
    "TT": { "phcode": "1868", "countryName": "Тринидад и Тобаго" },
    "TV": { "phcode": "688", "countryName": "Тувалу" },
    "TN": { "phcode": "216", "countryName": "Тунис" },
    "TM": { "phcode": "993", "countryName": "Туркменистан" },
    "TR": { "phcode": "90", "countryName": "Турция" },
    "UG": { "phcode": "256", "countryName": "Уганда" },
    "UZ": { "phcode": "998", "countryName": "Узбекистан" },
    // "UA": { "phcode": "380", "countryName": "Украина" },
    "WF": { "phcode": "681", "countryName": "Уоллис и Футуна" },
    // "UY": { "phcode": "598", "countryName": "Уругвай" },
    "FO": { "phcode": "298", "countryName": "Фарерские острова" },
    "FJ": { "phcode": "679", "countryName": "Фиджи" },
    "PH": { "phcode": "63", "countryName": "Филиппины" },
    "FI": { "phcode": "358", "countryName": "Финляндия" },
    "FK": { "phcode": "500", "countryName": "Фолклендские (Мальвинские) острова" },
    "FR": { "phcode": "33", "countryName": "Франция" },
    "GF": { "phcode": "594", "countryName": "Французская Гвиана" },
    "PF": { "phcode": "689", "countryName": "Французская Полинезия" },
    "TF": { "phcode": "689", "countryName": "Французские Южные территории" },
    "HR": { "phcode": "385", "countryName": "Хорватия" },
    "CF": { "phcode": "236", "countryName": "Центрально-Африканская Республика" },
    "TD": { "phcode": "235", "countryName": "Чад" },
    "ME": { "phcode": "382", "countryName": "Черногория" },
    "CZ": { "phcode": "420", "countryName": "Чешская Республика" },
    "CL": { "phcode": "56", "countryName": "Чили" },
    "CH": { "phcode": "41", "countryName": "Швейцария" },
    "SE": { "phcode": "46", "countryName": "Швеция" },
    "LK": { "phcode": "94", "countryName": "Шри-Ланка" },
    "EC": { "phcode": "593", "countryName": "Эквадор" },
    "GQ": { "phcode": "240", "countryName": "Экваториальная Гвинея" },
    "ER": { "phcode": "291", "countryName": "Эритрея" },
    "EE": { "phcode": "372", "countryName": "Эстония" },
    "ET": { "phcode": "251", "countryName": "Эфиопия" },
    "ZA": { "phcode": "27", "countryName": "Южная Африка" },
    "GS": { "phcode": "500", "countryName": "Южная Джорджия и Южные Сандвичевы Острова" },
    "KR": { "phcode": "82", "countryName": "Южная Корея" },
    "SS": { "phcode": "211", "countryName": "Южный Судан" },
    "JM": { "phcode": "1876", "countryName": "Ямайка" },
    "JP": { "phcode": "81", "countryName": "Япония" }
}